FROM {ARG_FROM}

ADD bin/{ARG_OS}_{ARG_ARCH}/ /goapp/bin/

EXPOSE {PORT}

WORKDIR /goapp/bin/
# This would be nicer as `nobody:nobody` but distroless has no such entries.
USER 65535:65535
ENV GIN_MODE release

ENTRYPOINT ["./{ARG_BIN}"]
